### PR TITLE
Add sorts

### PR DESCRIPTION
**Pull request by cdb1212**
Moves sorts to list component,
Implements alphabetical, user order, number of uses, last used, group, and plus/basic sorts
Saves user ordering of calls when creating templates or sessions
Adds basic/plus filter

### CODE REVIEW

**Comment by logand** [comment]
In the future, don't add me as a reviewer until a PR is done and ready for review.

**Comment by cdb1212** [comment]
This one is ready for review, it was the loading screen pull request that wasn't done yet

**Comment by cdb1212** [comment]
@logand

**Comment by logand** [comment]
So I'm going to approve this because it works well and adds functionality that you need for the filtering. As a follow-up, rather than doing it in this PR, I would like to DRY up the sorting functions in `List.js`. I believe that you only need 1 or 2 with different parameters since you can dynamically call attributes.

**Pull request merged**
